#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Dec 02 14:12:28 PST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 8e3d462baef24d79b8cf40cd4e4258c1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ScoreMatrixSqTb_behav xil_defaultlib.ScoreMatrixSqTb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 8e3d462baef24d79b8cf40cd4e4258c1 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot ScoreMatrixSqTb_behav xil_defaultlib.ScoreMatrixSqTb xil_defaultlib.glbl -log elaborate.log

