webtalk_init -webtalk_dir /home/jacob/Workspace/school/seniorproj/Blastn/hdl/vivado/Blastn.sim/sim_1/behav/xsim/xsim.dir/ScoreMatrixTb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 22 20:43:48 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "67f02b5e-d8d8-4c22-ba81-c755e501519a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e3d462baef24d79b8cf40cd4e4258c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "144" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1087.768 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.10_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128256_KB" -context "xsim\\usage"
webtalk_transmit -clientid 472391664 -regid "" -xml /home/jacob/Workspace/school/seniorproj/Blastn/hdl/vivado/Blastn.sim/sim_1/behav/xsim/xsim.dir/ScoreMatrixTb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jacob/Workspace/school/seniorproj/Blastn/hdl/vivado/Blastn.sim/sim_1/behav/xsim/xsim.dir/ScoreMatrixTb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jacob/Workspace/school/seniorproj/Blastn/hdl/vivado/Blastn.sim/sim_1/behav/xsim/xsim.dir/ScoreMatrixTb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
